"""Exporter framework (#014) and Markdown profile/timeline (#015) tests."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import pytest
from typer.testing import CliRunner

from experienceos.cli.app import app
from experienceos.exporters import default_exporter_registry
from experienceos.exporters.markdown import MarkdownExporter
from experienceos.storage import ExperienceStore

runner = CliRunner()


def full(result: Any) -> str:
    return result.output + (result.stderr or "")


@pytest.fixture
def two_records(cli_env, make_experience) -> tuple[str, str]:
    store = ExperienceStore(cli_env)
    active = make_experience(
        title="Campus Search",
        type="course_project",
        period={"start": "2023-01", "end": "2023-06"},
        role="engine lead",
        technology=["Python", "Whoosh"],
        contribution=["designed the inverted index"],
        result=["top-10 hit rate 92% in the demo"],
        evidence=[{"kind": "url", "location": "https://example.com/demo"}],
    )
    draft = make_experience(
        title="Secret Draft", period={"start": "2024-01", "end": None}, status="draft"
    )
    store.save(active)
    store.save(draft)
    return active.id, draft.id


class TestFramework:
    def test_markdown_registered_and_protocol_conformant(self) -> None:
        exporter = default_exporter_registry.get("markdown")
        assert exporter.name == "markdown"
        assert isinstance(exporter, MarkdownExporter)

    def test_unknown_exporter_lists_available(self, cli_env) -> None:
        result = runner.invoke(app, ["export", "nope"])
        output = full(result)
        assert result.exit_code == 1, output
        assert "unknown exporter 'nope'" in output
        assert "markdown" in output

    def test_list_flag(self, cli_env) -> None:
        result = runner.invoke(app, ["export", "--list"])
        assert result.exit_code == 0
        assert "markdown" in result.output

    def test_empty_selection_is_clean_exit(self, cli_env) -> None:
        result = runner.invoke(app, ["export", "markdown", "--out", "x.md"])
        assert result.exit_code == 0
        assert "No experiences match" in result.output


class TestMarkdownExport:
    def test_exports_active_records_only(
        self, cli_env, two_records, tmp_path: Path
    ) -> None:
        _active_id, _draft_id = two_records
        out = tmp_path / "profile.md"
        result = runner.invoke(app, ["export", "markdown", "--out", str(out)])
        assert result.exit_code == 0, full(result)
        assert f"-> {out}" in result.output
        content = out.read_text(encoding="utf-8")
        assert "Campus Search" in content
        assert "Secret Draft" not in content  # drafts never leak by default
        assert "- **Contribution**:" in content
        assert "  - designed the inverted index" in content
        assert "[url] https://example.com/demo" in content
        assert "record(s)" in content and "Generated by ExperienceOS" in content

    def test_status_filter_can_include_drafts(
        self, cli_env, two_records, tmp_path: Path
    ) -> None:
        _active_id, _draft_id = two_records
        out = tmp_path / "all.md"
        result = runner.invoke(
            app,
            ["export", "markdown", "--out", str(out), "--status", "draft"],
        )
        assert result.exit_code == 0, full(result)
        assert "Secret Draft" in out.read_text(encoding="utf-8")

    def test_type_filter_uses_search_query(
        self, cli_env, two_records, tmp_path: Path
    ) -> None:
        _active_id, _draft_id = two_records
        out = tmp_path / "filtered.md"
        result = runner.invoke(
            app, ["export", "markdown", "--out", str(out), "--type", "work"]
        )
        assert result.exit_code == 0
        assert "No experiences match" in result.output

    def test_timeline_groups_by_year(
        self, cli_env, two_records, tmp_path: Path
    ) -> None:
        out = tmp_path / "timeline.md"
        result = runner.invoke(
            app, ["export", "markdown", "--out", str(out), "--timeline"]
        )
        assert result.exit_code == 0, full(result)
        content = out.read_text(encoding="utf-8")
        # only the active record is exported by default: no 2024 section
        assert "## 2023" in content
        assert "## 2024" not in content
        assert "| Title | Type | Period |" in content
        assert "2023-01 ~ 2023-06" in content

    def test_empty_selection_rejected_at_exporter_level(self, tmp_path: Path) -> None:
        from experienceos.core.errors import ExportError

        with pytest.raises(ExportError, match="nothing to export"):
            MarkdownExporter().export([], tmp_path / "x.md")


class TestGoldenFile:
    def test_profile_matches_golden(
        self, cli_env, make_experience, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import experienceos.exporters.markdown as md_module

        monkeypatch.setattr(md_module, "_now", lambda: datetime(2026, 8, 29, 12, 0))
        store = ExperienceStore(cli_env)
        store.save(
            make_experience(
                title="Campus Search",
                type="course_project",
                period={"start": "2023-01", "end": "2023-06"},
                role="engine lead",
                context="database course project, team of three",
                description="a small search engine for campus documents",
                technology=["Python", "Whoosh"],
                contribution=["designed the inverted index and query pipeline"],
                challenge=["long-document recall was low"],
                solution=["jieba custom dictionary plus hybrid BM25 ranking"],
                result=["top-10 hit rate 92% in the course demo"],
                reflection="evaluation sets matter more than clever tricks",
            )
        )
        store.save(
            make_experience(
                title="Log Platform",
                type="personal",
                period={"start": "2022-03", "end": None},
                description="ClickHouse-backed log search",
                technology=["ClickHouse"],
                result=["ingested 10万 rows per day"],
                evidence=[
                    {
                        "kind": "url",
                        "location": "https://github.com/me/logplatform",
                        "description": "source repository",
                    }
                ],
            )
        )
        out = tmp_path / "golden.md"
        result = runner.invoke(app, ["export", "markdown", "--out", str(out)])
        assert result.exit_code == 0, full(result)
        golden = Path(__file__).parent / "fixtures" / "golden_profile.md"
        assert out.read_text(encoding="utf-8") == golden.read_text(encoding="utf-8")

    def test_golden_timeline(
        self, cli_env, make_experience, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import experienceos.exporters.markdown as md_module

        monkeypatch.setattr(md_module, "_now", lambda: datetime(2026, 8, 29, 12, 0))
        store = ExperienceStore(cli_env)
        store.save(make_experience(title="Later", period={"start": "2023-01", "end": None}))
        store.save(make_experience(title="Earlier", period={"start": "2022-05", "end": "2022-09"}))
        out = tmp_path / "golden.md"
        result = runner.invoke(
            app, ["export", "markdown", "--out", str(out), "--timeline"]
        )
        assert result.exit_code == 0, full(result)
        golden = Path(__file__).parent / "fixtures" / "golden_timeline.md"
        assert out.read_text(encoding="utf-8") == golden.read_text(encoding="utf-8")


class TestDefaultNaming:
    def test_default_target_in_cwd(
        self, cli_env, two_records, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.chdir(tmp_path)
        import importlib

        # patch via importlib: plain attribute chains resolve to the
        # Typer `app` instance because cli/__init__ re-exports `app`
        module = importlib.import_module("experienceos.cli.app")
        monkeypatch.setattr(module, "datetime", _FrozenDatetime)
        result = runner.invoke(app, ["export", "markdown"])
        assert result.exit_code == 0, full(result)
        expected = tmp_path / "experienceos-export-markdown-20260829-120000.md"
        assert expected.exists()
        assert str(expected) in result.output


class _FrozenDatetime(datetime):
    @classmethod
    def now(cls, *args: Any, **kwargs: Any) -> datetime:
        return cls(2026, 8, 29, 12, 0, 0)
