<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Experience profile — $count record(s)</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    margin: 0 auto; padding: 40px 24px 64px; max-width: 820px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif;
    font-size: 15px; line-height: 1.7; color: #252525; background: #fff;
  }
  h1 { font-size: 1.5rem; letter-spacing: -.3px; margin: 0 0 4px; }
  .footer { margin-top: 48px; padding-top: 14px; border-top: 1px solid #e9e9e7;
    color: #737373; font-size: .8125rem; }
  .entry { margin: 36px 0 44px; }
  .entry h2 { font-size: 1.125rem; margin: 0 0 2px; }
  .meta { margin: 0 0 10px; color: #737373; font-size: .875rem; }
  .context { color: #575757; }
  h3 { font-size: .9375rem; margin: 18px 0 6px; color: #444; }
  ul { margin: 0; padding-left: 22px; }
  li { margin: 4px 0; }
  blockquote { margin: 14px 0 0; padding: 2px 0 2px 14px; border-left: 3px solid #d4d4d0;
    color: #575757; font-style: italic; }
  a { color: inherit; text-underline-offset: 3px; }
  .kind { display: inline-block; min-width: 4.2em; color: #737373;
    font-size: .75rem; text-transform: uppercase; letter-spacing: .4px; }
  .local { color: #575757; }
  @media print {
    body { padding: 0; font-size: 11pt; max-width: none; }
    .entry { break-inside: avoid; }
    a { text-decoration: none; }
    .footer { border-color: #ccc; }
  }
</style>
</head>
<body>
<h1>Experience profile</h1>
<p class="meta">$count record(s) · exported $generated · generated by ExperienceOS</p>
$entries
<p class="footer">Exported by ExperienceOS — a faithful projection of locally stored,
evidence-backed experience records.</p>
</body>
</html>
